### ISSUE TITLE
Possible regression: Updating 2.8.0 to 2.9.0 causes "type annotations needed" for `BTreeSet::range` etc.

### ISSUE THREAD

**Issue by TonalidadeHidrica** [reem/rust-ordered-float#105]
See the following code:

```rust
use std::collections::BTreeSet;
use ordered_float::NotNan;

fn main() {
    let a = BTreeSet::<NotNan<f64>>::new();
    let b = a.range(..);
}
```

In 2.8.0, this code compiles.  In 2.9.0 and 2.10.0, it causes the following error:

![image](https://user-images.githubusercontent.com/47710717/148652164-4243d87b-da12-4da5-8d4c-70ef7e49a259.png)
<details><summary>Copyable text</summary>

```
error[E0283]: type annotations needed
 --> src/main.rs:6:15
  |
6 |     let b = a.range(..);
  |               ^^^^^ cannot infer type for type parameter `K` declared on the associated function `range`
  |
  = note: cannot satisfy `_: Ord`
```

</details>

I cannot figure out at all why this error happens, but this is indeed a regression.

```
$ rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)
```

**Comment by TonalidadeHidrica** [comment]
The workaround is to explicitly specify the type parameter `K`.

```rust
use std::collections::BTreeSet;
use ordered_float::NotNan;

fn main() {
    let a = BTreeSet::<NotNan<f64>>::new();
    let b = a.range::<NotNan<f64>, _>(..);
}
```

**Comment by mbrubeck** [comment]
Hmm, this was caused by #98.

**Comment by TonalidadeHidrica** [comment]
Isn't it strange that implementing a trait make type inference fail?  I'm wondering if this tends to happen, or it is a bug (or something can be improved) of Rust compiler.

**Comment by mbrubeck** [comment]
The [`BTreeSet::range`](https://doc.rust-lang.org/stable/std/collections/struct.BTreeSet.html#method.range) method is generic over a type `K: Ord` where `T: Borrow<K> + Ord`.  So it seems plausible that adding a new `Borrow` implementation to `NotNan` could allow calling this function with additional types.

However, `NotNan<f64>` only implements `Borrow<f64>`, and `f64` does not implement `Ord`.  So it should not affect this function call.  It seems the compiler is not smart enough to see this, or it is overly conservative since it believes that `f64` might implement `Ord` in the future.  I'm not sure which.

**Comment by mbrubeck** [comment]
I fixed this in ordered-float 3.0.0 by removing the impls that triggered it.

**Comment by mbrubeck** [comment]
Closed accidentally.  I meant to close #91, not this one.
